### ISSUE TITLE
Today DeepL is not working anymore 

### ISSUE THREAD

**Issue by FabioManoel1977** [leminhyen2/Sugoi-Japanese-Translator#3]
Today DeepL is not working anymore it is showing this error message, that it means that finally DeepL blocked Sugoi-Japanese-Translator ?

ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 30)
(node:10200) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'textContent' of null
    at __puppeteer_evaluation_script__:3:28
    at ExecutionContext._evaluateInternal (C:\Sugoi-Japanese-Translator-V3.0\backendServer\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (C:\Sugoi-Japanese-Translator-V3.0\backendServer\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async TranslatorCore.returnTranslationText (C:\Sugoi-Japanese-Translator-V3.0\backendServer\Program-Backend\Sugoi-Translator-Online\translatorCore.js:72:31)
    at async TranslatorCore.checkIfCurrentTranslationTextChanged (C:\Sugoi-Japanese-Translator-V3.0\backendServer\Program-Backend\Sugoi-Translator-Online\translatorCore.js:59:36)
    at async Timeout._onTimeout (C:\Sugoi-Japanese-Translator-V3.0\backendServer\Program-Backend\Sugoi-Translator-Online\main.js:32:26)
(node:10200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 31)

**Comment by leminhyen2** [comment]
Yea, I'm investigating this issue. Even Textractor is having this same program too. For now I would recommend people to use the offline model
